# Generated by Django 2.2.3 on 2019-12-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_auto_20191230_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribes',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscribes',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
