# Generated by Django 2.2.3 on 2019-12-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_auto_20191230_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribes',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribes',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
