# Generated by Django 2.2.3 on 2019-12-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('job', models.CharField(max_length=150)),
                ('level', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
