# Generated by Django 2.2.3 on 2019-12-31 18:58

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ee_control_upload', '0003_auto_20191231_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=smartfields.fields.FileField(upload_to='media'),
        ),
    ]
