# Generated by Django 2.2.3 on 2019-12-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee_control_upload', '0004_auto_20191231_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
