# Generated by Django 2.2.3 on 2019-12-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee_control_upload', '0002_auto_20191230_1455'),
        ('ee_control_find', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcv',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ee_control_upload.file'),
            preserve_default=False,
        ),
    ]
