# Generated by Django 2.2.3 on 2019-12-31 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee_control_find', '0002_savedcv_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcv',
            name='user',
        ),
        migrations.AlterField(
            model_name='savedcv',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee_control_upload.file'),
        ),
    ]
