# Generated by Django 2.2.3 on 2020-01-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee_control_find', '0004_auto_20191231_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=150)),
                ('employee', models.CharField(max_length=150)),
                ('cv', models.FileField(upload_to='')),
                ('job', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=150)),
                ('employee', models.CharField(max_length=150)),
                ('cv', models.FileField(upload_to='')),
                ('job', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=150)),
                ('employee', models.CharField(max_length=150)),
                ('cv', models.FileField(upload_to='')),
                ('job', models.CharField(max_length=150)),
            ],
        ),
    ]
